"""empty message

Revision ID: 2bdcb5eca9ac
Revises: 
Create Date: 2019-11-10 09:37:41.506491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bdcb5eca9ac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('manufacturers', sa.String(length=255), nullable=True),
    sa.Column('manufacturers_type', sa.String(length=255), nullable=True),
    sa.Column('manufacture_date', sa.DateTime(), nullable=True),
    sa.Column('disk', sa.String(length=255), nullable=True),
    sa.Column('cpu', sa.String(length=255), nullable=True),
    sa.Column('memory', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.Column('vm_status', sa.Integer(), nullable=True),
    sa.Column('sn', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=255), nullable=True),
    sa.Column('mac_address', sa.String(length=255), nullable=True),
    sa.Column('Product_id', sa.Integer(), nullable=True),
    sa.Column('Service_id', sa.Integer(), nullable=True),
    sa.Column('sa_manager', sa.String(length=255), nullable=True),
    sa.Column('dev_manager', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server')
    # ### end Alembic commands ###
