"""empty message

Revision ID: 479baa8e4440
Revises: f702b3618084
Create Date: 2019-12-13 14:50:19.972682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479baa8e4440'
down_revision = 'f702b3618084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gongdan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gongdan')
    # ### end Alembic commands ###
