"""empty message

Revision ID: 629f0ffa37e2
Revises: 479baa8e4440
Create Date: 2019-12-13 15:46:54.305688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629f0ffa37e2'
down_revision = '479baa8e4440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gongdan', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gongdan', 'status')
    # ### end Alembic commands ###
