"""empty message

Revision ID: 8f2b1243a0a1
Revises: 2bdcb5eca9ac
Create Date: 2019-11-18 10:03:24.707490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f2b1243a0a1'
down_revision = '2bdcb5eca9ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.String(length=20), nullable=True, comment='业务线名称'),
    sa.Column('pid', sa.Integer(), nullable=True, comment='顶级业务线'),
    sa.Column('module_letter', sa.String(length=20), nullable=True, comment='业务线英文缩写'),
    sa.Column('dev_interface', sa.String(length=200), nullable=True, comment='业务线开发负责人'),
    sa.Column('op_interface', sa.String(length=100), nullable=True, comment='业务线运维负责人'),
    sa.Column('commentd', sa.String(length=100), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('server', 'sa_manager')
    op.drop_column('server', 'dev_manager')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('dev_manager', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('server', sa.Column('sa_manager', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('product')
    # ### end Alembic commands ###
