"""empty message

Revision ID: aaf2dcff354f
Revises: 629f0ffa37e2
Create Date: 2019-12-15 16:15:28.622545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf2dcff354f'
down_revision = '629f0ffa37e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gongdan', sa.Column('applicant', sa.Integer(), nullable=True))
    op.add_column('gongdan', sa.Column('create_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gongdan', 'create_time')
    op.drop_column('gongdan', 'applicant')
    # ### end Alembic commands ###
