"""empty message

Revision ID: e3c5d7ba9169
Revises: 1a02ad1f5854
Create Date: 2019-11-29 12:54:45.225294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3c5d7ba9169'
down_revision = '1a02ad1f5854'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zabbix_host',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('hostid', sa.String(length=255), nullable=True),
    sa.Column('available', sa.Integer(), nullable=True),
    sa.Column('groups', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zabbix_host')
    # ### end Alembic commands ###
