"""empty message

Revision ID: f702b3618084
Revises: e3c5d7ba9169
Create Date: 2019-12-06 14:18:34.736385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f702b3618084'
down_revision = 'e3c5d7ba9169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zabbix_host', sa.Column('maintenance_status', sa.Integer(), nullable=True))
    op.add_column('zabbix_host', sa.Column('maintenanceid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zabbix_host', 'maintenanceid')
    op.drop_column('zabbix_host', 'maintenance_status')
    # ### end Alembic commands ###
